### ISSUE TITLE
Add PIN support for alarm arm/disarm ?

### ISSUE THREAD

**Issue by shanelord01** [danTapps/homebridge-hubitat-makerapi#2]
Hi,

Thanks so much for this - works brilliantly.

One thing would be great to have is pin support for arm/disarm. I believe Home Assistant have this in their Homekit support so am assuming could be added?

https://www.home-assistant.io/components/homekit/

Thanks.

**Comment by danTapps** [comment]
This is the other way around. Home Assistant might require a PIN to set the arm/disarm state and this implementation allows HomeKit to send that PIN. There is currently no way to request a PIN to be entered by the User.
